name: Download, Unzip and Save Lobbyist Registry Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  download_lobby_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TORONTOLOBBYISTREGISTRYDATA }}
      - name: Checkout TorontoLobbyistRegistry
        uses: actions/checkout@v2
        with:
          repository: 'RamVasuthevan/TorontoLobbyistRegistry'
          token: ${{ secrets.PAT }}
          path: TorontoLobbyistRegistry
      - name: Echo commit hash of TorontoLobbyistRegistry
        run: |
          cd TorontoLobbyistRegistry
          TorontoLobbyistRegistry_commit_hash=$(git rev-parse HEAD)
          echo "TorontoLobbyistRegistry_commit_hash=${TorontoLobbyistRegistry_commit_hash}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies with pipenv
        run: |
          cd TorontoLobbyistRegistry
          pipenv install
      - name: Run Python script to download and unzip files
        run: |
          cd TorontoLobbyistRegistry
          pipenv run python download_and_extract.py 
          cd ..
          mv TorontoLobbyistRegistry/lobbyactivity-active.xml lobbyactivity-active.xml
          mv TorontoLobbyistRegistry/lobbyactivity-closed.xml lobbyactivity-closed.xml
          mv TorontoLobbyistRegistry/lobbyist-registry-readme.xls lobbyist-registry-readme.xls
          mv TorontoLobbyistRegistry/open-data-response.json open-data-response.json
          mv TorontoLobbyistRegistry/"Lobbyist Registry Activity.zip" "Lobbyist Registry Activity.zip"
          rm -rf TorontoLobbyistRegistry
      - name: Commit and push if files changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add lobbyactivity-active.xml
          git add lobbyactivity-closed.xml
          git add lobbyist-registry-readme.xls
          git add open-data-response.json
          git add "Lobbyist Registry Activity.zip"
          timestamp=$(date -u)
          git commit -m "Dowloaded: ${timestamp}: commit: ${{env.TorontoLobbyistRegistry_commit_hash}}" || exit 0
          git push
